<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Surah;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['nama'=>'Al-Fatihah','jumlah_ayat'=>7,'urutan'=>1],
            ['nama'=>'Al-Baqarah','jumlah_ayat'=>286,'urutan'=>2],
            ['nama'=>'Ali Imran','jumlah_ayat'=>200,'urutan'=>3],
            ['nama'=>'An-Nisa','jumlah_ayat'=>176,'urutan'=>4],
            ['nama'=>'Al-Maidah','jumlah_ayat'=>120,'urutan'=>5],
            ['nama'=>'Al-An’am','jumlah_ayat'=>165,'urutan'=>6],
            ['nama'=>'Al-A’raf','jumlah_ayat'=>206,'urutan'=>7],
            ['nama'=>'Al-Anfal','jumlah_ayat'=>75,'urutan'=>8],
            ['nama'=>'At-Taubah','jumlah_ayat'=>129,'urutan'=>9],
            ['nama'=>'Yunus','jumlah_ayat'=>109,'urutan'=>10],
            ['nama'=>'Hud','jumlah_ayat'=>123,'urutan'=>11],
            ['nama'=>'Yusuf','jumlah_ayat'=>111,'urutan'=>12],
            ['nama'=>'Ar-Ra’d','jumlah_ayat'=>43,'urutan'=>13],
            ['nama'=>'Ibrahim','jumlah_ayat'=>52,'urutan'=>14],
            ['nama'=>'Al-Hijr','jumlah_ayat'=>99,'urutan'=>15],
            ['nama'=>'An-Nahl','jumlah_ayat'=>128,'urutan'=>16],
            ['nama'=>'Al-Isra','jumlah_ayat'=>111,'urutan'=>17],
            ['nama'=>'Al-Kahfi','jumlah_ayat'=>110,'urutan'=>18],
            ['nama'=>'Maryam','jumlah_ayat'=>98,'urutan'=>19],
            ['nama'=>'Ta-Ha','jumlah_ayat'=>135,'urutan'=>20],
            ['nama'=>'Al-Anbiya','jumlah_ayat'=>112,'urutan'=>21],
            ['nama'=>'Al-Hajj','jumlah_ayat'=>78,'urutan'=>22],
            ['nama'=>'Al-Mu’minun','jumlah_ayat'=>118,'urutan'=>23],
            ['nama'=>'An-Nur','jumlah_ayat'=>64,'urutan'=>24],
            ['nama'=>'Al-Furqan','jumlah_ayat'=>77,'urutan'=>25],
            ['nama'=>'Ash-Shu’ara','jumlah_ayat'=>227,'urutan'=>26],
            ['nama'=>'An-Naml','jumlah_ayat'=>93,'urutan'=>27],
            ['nama'=>'Al-Qasas','jumlah_ayat'=>88,'urutan'=>28],
            ['nama'=>'Al-Ankabut','jumlah_ayat'=>69,'urutan'=>29],
            ['nama'=>'Ar-Rum','jumlah_ayat'=>60,'urutan'=>30],
            ['nama'=>'Luqman','jumlah_ayat'=>34,'urutan'=>31],
            ['nama'=>'As-Sajdah','jumlah_ayat'=>30,'urutan'=>32],
            ['nama'=>'Al-Ahzab','jumlah_ayat'=>73,'urutan'=>33],
            ['nama'=>'Saba','jumlah_ayat'=>54,'urutan'=>34],
            ['nama'=>'Fatir','jumlah_ayat'=>45,'urutan'=>35],
            ['nama'=>'Ya-Sin','jumlah_ayat'=>83,'urutan'=>36],
            ['nama'=>'As-Saffat','jumlah_ayat'=>182,'urutan'=>37],
            ['nama'=>'Sad','jumlah_ayat'=>88,'urutan'=>38],
            ['nama'=>'Az-Zumar','jumlah_ayat'=>75,'urutan'=>39],
            ['nama'=>'Ghafir','jumlah_ayat'=>85,'urutan'=>40],
            ['nama'=>'Fussilat','jumlah_ayat'=>54,'urutan'=>41],
            ['nama'=>'Ash-Shura','jumlah_ayat'=>53,'urutan'=>42],
            ['nama'=>'Az-Zukhruf','jumlah_ayat'=>89,'urutan'=>43],
            ['nama'=>'Ad-Dukhan','jumlah_ayat'=>59,'urutan'=>44],
            ['nama'=>'Al-Jathiyah','jumlah_ayat'=>37,'urutan'=>45],
            ['nama'=>'Al-Ahqaf','jumlah_ayat'=>35,'urutan'=>46],
            ['nama'=>'Muhammad','jumlah_ayat'=>38,'urutan'=>47],
            ['nama'=>'Al-Fath','jumlah_ayat'=>29,'urutan'=>48],
            ['nama'=>'Al-Hujurat','jumlah_ayat'=>18,'urutan'=>49],
            ['nama'=>'Qaf','jumlah_ayat'=>45,'urutan'=>50],
            ['nama'=>'Adh-Dhariyat','jumlah_ayat'=>60,'urutan'=>51],
            ['nama'=>'At-Tur','jumlah_ayat'=>49,'urutan'=>52],
            ['nama'=>'An-Najm','jumlah_ayat'=>62,'urutan'=>53],
            ['nama'=>'Al-Qamar','jumlah_ayat'=>55,'urutan'=>54],
            ['nama'=>'Ar-Rahman','jumlah_ayat'=>78,'urutan'=>55],
            ['nama'=>'Al-Waqiah','jumlah_ayat'=>96,'urutan'=>56],
            ['nama'=>'Al-Hadid','jumlah_ayat'=>29,'urutan'=>57],
            ['nama'=>'Al-Mujadilah','jumlah_ayat'=>22,'urutan'=>58],
            ['nama'=>'Al-Hashr','jumlah_ayat'=>24,'urutan'=>59],
            ['nama'=>'Al-Mumtahanah','jumlah_ayat'=>13,'urutan'=>60],
            ['nama'=>'As-Saff','jumlah_ayat'=>14,'urutan'=>61],
            ['nama'=>'Al-Jumuah','jumlah_ayat'=>11,'urutan'=>62],
            ['nama'=>'Al-Munafiqun','jumlah_ayat'=>11,'urutan'=>63],
            ['nama'=>'At-Taghabun','jumlah_ayat'=>18,'urutan'=>64],
            ['nama'=>'At-Talaq','jumlah_ayat'=>12,'urutan'=>65],
            ['nama'=>'At-Tahrim','jumlah_ayat'=>12,'urutan'=>66],
            ['nama'=>'Al-Mulk','jumlah_ayat'=>30,'urutan'=>67],
            ['nama'=>'Al-Qalam','jumlah_ayat'=>52,'urutan'=>68],
            ['nama'=>'Al-Haqqah','jumlah_ayat'=>52,'urutan'=>69],
            ['nama'=>'Al-Ma’arij','jumlah_ayat'=>44,'urutan'=>70],
            ['nama'=>'Nuh','jumlah_ayat'=>28,'urutan'=>71],
            ['nama'=>'Al-Jinn','jumlah_ayat'=>28,'urutan'=>72],
            ['nama'=>'Al-Muzzammil','jumlah_ayat'=>20,'urutan'=>73],
            ['nama'=>'Al-Muddathir','jumlah_ayat'=>56,'urutan'=>74],
            ['nama'=>'Al-Qiyamah','jumlah_ayat'=>40,'urutan'=>75],
            ['nama'=>'Al-Insan','jumlah_ayat'=>31,'urutan'=>76],
            ['nama'=>'Al-Mursalat','jumlah_ayat'=>50,'urutan'=>77],
            ['nama'=>'An-Naba','jumlah_ayat'=>40,'urutan'=>78],
            ['nama'=>'An-Naziat','jumlah_ayat'=>46,'urutan'=>79],
            ['nama'=>'Abasa','jumlah_ayat'=>42,'urutan'=>80],
            ['nama'=>'At-Takwir','jumlah_ayat'=>29,'urutan'=>81],
            ['nama'=>'Al-Infitar','jumlah_ayat'=>19,'urutan'=>82],
            ['nama'=>'Al-Mutaffifin','jumlah_ayat'=>36,'urutan'=>83],
            ['nama'=>'Al-Inshiqaq','jumlah_ayat'=>25,'urutan'=>84],
            ['nama'=>'Al-Buruj','jumlah_ayat'=>22,'urutan'=>85],
            ['nama'=>'At-Tariq','jumlah_ayat'=>17,'urutan'=>86],
            ['nama'=>'Al-Ala','jumlah_ayat'=>19,'urutan'=>87],
            ['nama'=>'Al-Ghashiyah','jumlah_ayat'=>26,'urutan'=>88],
            ['nama'=>'Al-Fajr','jumlah_ayat'=>30,'urutan'=>89],
            ['nama'=>'Al-Balad','jumlah_ayat'=>20,'urutan'=>90],
            ['nama'=>'Ash-Shams','jumlah_ayat'=>15,'urutan'=>91],
            ['nama'=>'Al-Lail','jumlah_ayat'=>21,'urutan'=>92],
            ['nama'=>'Ad-Duha','jumlah_ayat'=>11,'urutan'=>93],
            ['nama'=>'Ash-Sharh','jumlah_ayat'=>8,'urutan'=>94],
            ['nama'=>'At-Tin','jumlah_ayat'=>8,'urutan'=>95],
            ['nama'=>'Al-Alaq','jumlah_ayat'=>19,'urutan'=>96],
            ['nama'=>'Al-Qadr','jumlah_ayat'=>5,'urutan'=>97],
            ['nama'=>'Al-Bayyinah','jumlah_ayat'=>8,'urutan'=>98],
            ['nama'=>'Az-Zalzalah','jumlah_ayat'=>8,'urutan'=>99],
            ['nama'=>'Al-Adiyat','jumlah_ayat'=>11,'urutan'=>100],
            ['nama'=>'Al-Qariah','jumlah_ayat'=>11,'urutan'=>101],
            ['nama'=>'At-Takathur','jumlah_ayat'=>8,'urutan'=>102],
            ['nama'=>'Al-Asr','jumlah_ayat'=>3,'urutan'=>103],
            ['nama'=>'Al-Humazah','jumlah_ayat'=>9,'urutan'=>104],
            ['nama'=>'Al-Fil','jumlah_ayat'=>5,'urutan'=>105],
            ['nama'=>'Quraisy','jumlah_ayat'=>4,'urutan'=>106],
            ['nama'=>'Al-Maun','jumlah_ayat'=>7,'urutan'=>107],
            ['nama'=>'Al-Kautsar','jumlah_ayat'=>3,'urutan'=>108],
            ['nama'=>'Al-Kafirun','jumlah_ayat'=>6,'urutan'=>109],
            ['nama'=>'An-Nasr','jumlah_ayat'=>3,'urutan'=>110],
            ['nama'=>'Al-Lahab','jumlah_ayat'=>5,'urutan'=>111],
            ['nama'=>'Al-Ikhlas','jumlah_ayat'=>4,'urutan'=>112],
            ['nama'=>'Al-Falaq','jumlah_ayat'=>5,'urutan'=>113],
            ['nama'=>'An-Nas','jumlah_ayat'=>6,'urutan'=>114],
        ];

        foreach ($data as $item) {
            Surah::updateOrCreate(
                ['urutan' => $item['urutan']],
                $item
            );
        }
    }
}